name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}:latest
   
   deploy:
    name: remote to host
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script: |
            "docker run --name calc -d -p 5000:5000 elleath/calculator:latest"
            "curl "localhost:5000/?num1=5&num2=10&operation=add""
            "docker stop calc"
            "docker rm calc"
            
      - name: Print info
        run: echo "Deployed OK"
    

  
