name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}:latest
   
   test:
    needs: build
    runs-on: ubuntu-latest
    container: elleath/calculator:latest
    steps:
      - name: Make container
        run: |
           curl -X POST -d 'num1=5&num2=6&operation=add' localhost:5000
    

  
