name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_NAME }}:latest
   
   deploy:
    name: remote to host
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script:
            "docker run -d -p 5000:5000 ${{ secrets.DOCKER_NAME }}:latest"
      - name: Print info
        run: echo "Deployed OK"
    

  
